2024-11-11 09:11:44 - __main__ - INFO - app started
2024-11-11 09:11:44 - portSelector - INFO - ports refreshed
2024-11-11 09:11:51 - portSelector - INFO - no boards connected
2024-11-11 09:11:52 - __main__ - INFO - gui built
2024-11-11 09:11:54 - __main__ - INFO - start button clicked
2024-11-11 09:11:54 - __main__ - INFO - check if ports are selected
2024-11-11 09:11:54 - __main__ - INFO - serial worker started successfully
2024-11-11 09:11:54 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 09:11:54 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 09:11:54 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 09:11:54 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 09:11:54 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 09:12:40 - __main__ - INFO - app started
2024-11-11 09:12:40 - portSelector - INFO - ports refreshed
2024-11-11 09:12:42 - portSelector - INFO - no boards connected
2024-11-11 09:12:42 - __main__ - INFO - gui built
2024-11-11 09:12:46 - __main__ - INFO - start button clicked
2024-11-11 09:12:46 - __main__ - INFO - check if ports are selected
2024-11-11 09:12:46 - __main__ - INFO - serial worker started successfully
2024-11-11 09:12:46 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 09:12:46 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 09:12:46 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 09:12:46 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 09:12:46 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 09:12:58 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 09:12:58 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:04:42 - __main__ - INFO - app started
2024-11-11 10:04:42 - portSelector - INFO - ports refreshed
2024-11-11 10:04:44 - portSelector - INFO - no boards connected
2024-11-11 10:04:44 - __main__ - INFO - gui built
2024-11-11 10:04:50 - __main__ - INFO - start button clicked
2024-11-11 10:04:50 - __main__ - INFO - check if ports are selected
2024-11-11 10:04:50 - __main__ - INFO - serial worker started successfully
2024-11-11 10:04:50 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:04:50 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:04:50 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:04:50 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:04:50 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:05:06 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 10:05:06 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:07:51 - __main__ - INFO - app started
2024-11-11 10:07:51 - portSelector - INFO - ports refreshed
2024-11-11 10:07:53 - portSelector - INFO - no boards connected
2024-11-11 10:07:54 - __main__ - INFO - gui built
2024-11-11 10:07:57 - __main__ - INFO - start button clicked
2024-11-11 10:07:57 - __main__ - INFO - check if ports are selected
2024-11-11 10:07:57 - __main__ - INFO - serial worker started successfully
2024-11-11 10:07:57 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:07:57 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:07:57 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:07:57 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:07:57 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:08:04 - portSelector - INFO - ports refreshed
2024-11-11 10:08:04 - __main__ - INFO - start button re-enabled
2024-11-11 10:08:05 - portSelector - INFO - no boards connected
2024-11-11 10:08:30 - serialCaptureWorker - INFO - emergency stop should be sending now
2024-11-11 10:08:30 - serialCaptureWorker - WARNING - serial not open
2024-11-11 10:08:30 - serialCaptureWorker - INFO - emergency stop issued
2024-11-11 10:08:40 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 10:08:40 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:12:07 - __main__ - INFO - app started
2024-11-11 10:12:07 - portSelector - INFO - ports refreshed
2024-11-11 10:12:11 - portSelector - INFO - no boards connected
2024-11-11 10:12:12 - __main__ - INFO - gui built
2024-11-11 10:12:16 - __main__ - INFO - start button clicked
2024-11-11 10:12:16 - __main__ - INFO - check if ports are selected
2024-11-11 10:12:16 - __main__ - INFO - serial worker started successfully
2024-11-11 10:12:16 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:12:16 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:12:16 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:12:16 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:12:16 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:12:21 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 10:12:21 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:12:22 - __main__ - ERROR - no serial connection
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\main.py", line 284, in on_run_button_clicked
    self.check_temp()  # check if desired temp is not too far away from current temp, and let user decide
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\main.py", line 440, in check_temp
    if self.current_temperature - first_temp >= 10:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
2024-11-11 10:12:58 - __main__ - INFO - app started
2024-11-11 10:12:58 - portSelector - INFO - ports refreshed
2024-11-11 10:13:00 - portSelector - INFO - no boards connected
2024-11-11 10:13:01 - __main__ - INFO - gui built
2024-11-11 10:13:06 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 10:13:06 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:13:12 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 10:13:12 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:13:15 - __main__ - INFO - start button clicked
2024-11-11 10:13:15 - __main__ - INFO - check if ports are selected
2024-11-11 10:13:15 - __main__ - INFO - serial worker started successfully
2024-11-11 10:13:15 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:13:15 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:13:15 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:13:15 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:13:15 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:13:20 - jsonFunctionality - INFO - C:/Users/owenk/OneDrive/Desktop/Arduino/temperature chamber/temperature_chamber/tests/alphabet/alphabet_test.json
2024-11-11 10:13:20 - jsonFunctionality - INFO - test directory updated to: C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\tests but with correct forward slashes
2024-11-11 10:13:22 - __main__ - ERROR - no serial connection
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\main.py", line 284, in on_run_button_clicked
    self.check_temp()  # check if desired temp is not too far away from current temp, and let user decide
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\main.py", line 441, in check_temp
    if self.current_temperature - first_temp >= 10:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
2024-11-11 10:14:19 - __main__ - INFO - app started
2024-11-11 10:14:19 - portSelector - INFO - ports refreshed
2024-11-11 10:14:21 - portSelector - INFO - no boards connected
2024-11-11 10:14:22 - __main__ - INFO - gui built
2024-11-11 10:14:24 - __main__ - INFO - start button clicked
2024-11-11 10:14:24 - __main__ - INFO - check if ports are selected
2024-11-11 10:14:24 - __main__ - INFO - serial worker started successfully
2024-11-11 10:14:24 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:14:24 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:14:24 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:14:25 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:14:25 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:17:48 - __main__ - INFO - app started
2024-11-11 10:17:48 - portSelector - INFO - ports refreshed
2024-11-11 10:17:51 - portSelector - INFO - no boards connected
2024-11-11 10:17:51 - __main__ - INFO - gui built
2024-11-11 10:17:53 - __main__ - INFO - start button clicked
2024-11-11 10:17:53 - __main__ - INFO - check if ports are selected
2024-11-11 10:17:53 - __main__ - INFO - serial worker started successfully
2024-11-11 10:17:53 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:17:53 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:17:53 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:17:53 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:17:53 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:17:58 - __main__ - INFO - start button clicked
2024-11-11 10:17:58 - __main__ - INFO - check if ports are selected
2024-11-11 10:18:03 - __main__ - INFO - app started
2024-11-11 10:18:03 - portSelector - INFO - ports refreshed
2024-11-11 10:18:05 - portSelector - INFO - no boards connected
2024-11-11 10:18:06 - __main__ - INFO - gui built
2024-11-11 10:18:08 - __main__ - INFO - start button clicked
2024-11-11 10:18:08 - __main__ - INFO - check if ports are selected
2024-11-11 10:18:08 - __main__ - INFO - serial worker started successfully
2024-11-11 10:18:08 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:18:08 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:18:08 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:18:08 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:18:08 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:19:32 - __main__ - INFO - app started
2024-11-11 10:19:32 - portSelector - INFO - ports refreshed
2024-11-11 10:19:34 - portSelector - INFO - no boards connected
2024-11-11 10:19:34 - __main__ - INFO - gui built
2024-11-11 10:19:36 - __main__ - INFO - start button clicked
2024-11-11 10:19:36 - __main__ - INFO - check if ports are selected
2024-11-11 10:19:36 - __main__ - INFO - serial worker started successfully
2024-11-11 10:19:36 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:19:36 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:19:36 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:19:36 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:19:36 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:19:41 - __main__ - INFO - start button clicked
2024-11-11 10:19:41 - __main__ - INFO - check if ports are selected
2024-11-11 10:19:47 - portSelector - INFO - ports refreshed
2024-11-11 10:19:47 - __main__ - INFO - start button re-enabled
2024-11-11 10:19:49 - portSelector - INFO - no boards connected
2024-11-11 10:19:49 - __main__ - INFO - start button clicked
2024-11-11 10:19:49 - __main__ - INFO - check if ports are selected
2024-11-11 10:19:54 - __main__ - INFO - app started
2024-11-11 10:19:55 - portSelector - INFO - ports refreshed
2024-11-11 10:19:57 - portSelector - INFO - no boards connected
2024-11-11 10:19:57 - __main__ - INFO - gui built
2024-11-11 10:19:59 - __main__ - INFO - start button clicked
2024-11-11 10:19:59 - __main__ - INFO - check if ports are selected
2024-11-11 10:19:59 - __main__ - INFO - serial worker started successfully
2024-11-11 10:19:59 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 10:19:59 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:19:59 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 10:19:59 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 10:19:59 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 10:20:02 - __main__ - INFO - start button clicked
2024-11-11 10:20:02 - __main__ - INFO - check if ports are selected
2024-11-11 10:20:52 - __main__ - INFO - app started
2024-11-11 10:20:52 - portSelector - INFO - ports refreshed
2024-11-11 10:20:54 - portSelector - INFO - no boards connected
2024-11-11 10:20:54 - __main__ - INFO - gui built
2024-11-11 10:48:02 - __main__ - INFO - app started
2024-11-11 10:48:02 - portSelector - INFO - ports refreshed
2024-11-11 10:48:05 - portSelector - INFO - no boards connected
2024-11-11 10:48:20 - __main__ - INFO - app started
2024-11-11 10:48:20 - portSelector - INFO - ports refreshed
2024-11-11 10:48:22 - portSelector - INFO - no boards connected
2024-11-11 10:48:35 - __main__ - INFO - app started
2024-11-11 10:48:35 - portSelector - INFO - ports refreshed
2024-11-11 10:48:37 - portSelector - INFO - no boards connected
2024-11-11 10:51:06 - __main__ - INFO - app started
2024-11-11 10:51:06 - portSelector - INFO - ports refreshed
2024-11-11 10:51:08 - portSelector - INFO - no boards connected
2024-11-11 10:51:08 - __main__ - INFO - gui built
2024-11-11 10:52:03 - __main__ - INFO - app started
2024-11-11 10:52:03 - portSelector - INFO - ports refreshed
2024-11-11 10:52:05 - portSelector - INFO - no boards connected
2024-11-11 10:52:05 - __main__ - INFO - gui built
2024-11-11 10:56:41 - __main__ - INFO - app started
2024-11-11 10:56:41 - portSelector - INFO - ports refreshed
2024-11-11 10:56:43 - portSelector - INFO - no boards connected
2024-11-11 10:56:44 - __main__ - INFO - gui built
2024-11-11 11:05:57 - __main__ - INFO - app started
2024-11-11 11:05:57 - portSelector - INFO - ports refreshed
2024-11-11 11:05:59 - portSelector - INFO - no boards connected
2024-11-11 11:05:59 - __main__ - INFO - gui built
2024-11-11 11:06:01 - __main__ - INFO - start button clicked
2024-11-11 11:06:01 - __main__ - INFO - check if ports are selected
2024-11-11 11:06:01 - __main__ - INFO - serial worker started successfully
2024-11-11 11:06:01 - __main__ - INFO - qtimer started to check for pings every 5 seconds
2024-11-11 11:06:01 - testBoardWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\testBoardWorker.py", line 33, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 11:06:01 - testBoardWorker - ERROR - test board worker failed to connect to COM7
2024-11-11 11:06:02 - serialCaptureWorker - ERROR - error
Traceback (most recent call last):
  File "C:\Users\owenk\OneDrive\Desktop\Arduino\temperature chamber\temperature_chamber\interface\pyqt5\t-chamber\serialCaptureWorker.py", line 75, in serial_setup
    self.ser = serial.Serial(self.port, self.baudrate, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\owenk\anaconda3\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM15': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-11-11 11:06:02 - serialCaptureWorker - ERROR - failed to connect to COM15
2024-11-11 11:07:32 - __main__ - INFO - app started
2024-11-11 11:07:32 - portSelector - INFO - ports refreshed
2024-11-11 11:07:34 - portSelector - INFO - no boards connected
2024-11-11 11:07:34 - __main__ - INFO - gui built
2024-11-11 11:08:11 - __main__ - INFO - app started
2024-11-11 11:08:11 - portSelector - INFO - ports refreshed
2024-11-11 11:08:13 - portSelector - INFO - no boards connected
2024-11-11 11:08:13 - __main__ - INFO - gui built
2024-11-11 11:12:02 - __main__ - INFO - app started
2024-11-11 11:12:02 - portSelector - INFO - ports refreshed
2024-11-11 11:12:05 - portSelector - INFO - no boards connected
2024-11-11 11:12:05 - __main__ - INFO - gui built
2024-11-11 11:18:06 - __main__ - INFO - app started
2024-11-11 11:18:07 - portSelector - INFO - ports refreshed
2024-11-11 11:18:09 - portSelector - INFO - no boards connected
2024-11-11 11:18:09 - __main__ - INFO - gui built
2024-11-11 11:32:14 - __main__ - INFO - app started
2024-11-11 11:32:14 - portSelector - INFO - ports refreshed
2024-11-11 11:32:16 - portSelector - INFO - no boards connected
2024-11-11 11:33:22 - __main__ - INFO - app started
2024-11-11 11:33:22 - portSelector - INFO - ports refreshed
2024-11-11 11:33:24 - portSelector - INFO - no boards connected
2024-11-11 11:35:14 - __main__ - INFO - app started
2024-11-11 11:35:14 - portSelector - INFO - ports refreshed
2024-11-11 11:35:16 - portSelector - INFO - no boards connected
2024-11-11 11:35:16 - __main__ - INFO - gui built
